//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadPizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PEDIDO
    {
        public int detalle_id { get; set; }
        public int pedido_id { get; set; }
        public int platillo_id { get; set; }
        public int cantidad { get; set; }
        public decimal precio_unitario { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PLATILLO PLATILLO { get; set; }
    }
}
