//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadPizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESENA
    {
        public int resena_id { get; set; }
        public int usuario_id { get; set; }
        public int pedido_id { get; set; }
        public byte calificacion { get; set; }
        public string comentario { get; set; }
        public System.DateTime fecha { get; set; }
        public bool estado_registro { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
