//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadPizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioCliente
    {
        public int id { get; set; }
        public int idCliente { get; set; }
        public string usuarioLogin { get; set; }
        public string clave { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
