// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sis457_pizzeria.Web.Data;

#nullable disable

namespace sis457_pizzeria.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Ingrediente", b =>
                {
                    b.Property<int>("IngredienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredienteId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioAdicional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IngredienteId");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Masa", b =>
                {
                    b.Property<int>("MasaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasaId"));

                    b.Property<decimal>("MultiplicadorPrecio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasaId");

                    b.ToTable("Masas");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PedidoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PizzaId"));

                    b.Property<int>("MasaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TamanoId")
                        .HasColumnType("int");

                    b.HasKey("PizzaId");

                    b.HasIndex("MasaId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("TamanoId");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.PizzaIngrediente", b =>
                {
                    b.Property<int>("PizzaIngredienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PizzaIngredienteId"));

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.HasKey("PizzaIngredienteId");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaIngredientes");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Tamano", b =>
                {
                    b.Property<int>("TamanoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TamanoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MultiplicadorPrecio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TamanoId");

                    b.ToTable("Tamanos");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Pedido", b =>
                {
                    b.HasOne("sis457_pizzeria.Web.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Pizza", b =>
                {
                    b.HasOne("sis457_pizzeria.Web.Models.Masa", "Masa")
                        .WithMany("Pizzas")
                        .HasForeignKey("MasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sis457_pizzeria.Web.Models.Pedido", null)
                        .WithMany("Pizzas")
                        .HasForeignKey("PedidoId");

                    b.HasOne("sis457_pizzeria.Web.Models.Tamano", "Tamano")
                        .WithMany("Pizzas")
                        .HasForeignKey("TamanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Masa");

                    b.Navigation("Tamano");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.PizzaIngrediente", b =>
                {
                    b.HasOne("sis457_pizzeria.Web.Models.Ingrediente", "Ingrediente")
                        .WithMany("PizzaIngredientes")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sis457_pizzeria.Web.Models.Pizza", "Pizza")
                        .WithMany("PizzaIngredientes")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Ingrediente", b =>
                {
                    b.Navigation("PizzaIngredientes");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Masa", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Pedido", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Pizza", b =>
                {
                    b.Navigation("PizzaIngredientes");
                });

            modelBuilder.Entity("sis457_pizzeria.Web.Models.Tamano", b =>
                {
                    b.Navigation("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
